package com.sample
 
import com.sample.SUVRecommendation.Question;
 
rule "Not off road"
    when
        q: Question(chosen==0);
    then
        q.setValues("So wait, why are you buying an SUV?",5,q.getAnswers(),false,0);
        System.out.println("So wait, why are you buying an SUV?");
        update(q);
end

rule "Style"
    when
        q: Question(chosen==0);
    then
        q.setValues("What do you like about the style?",4,q.getAnswers(),false,0);
        System.out.println("What do you like about the style?");
        update(q);
end
